docs_dir: content
site_name: Digital Technologies Wiki
site_url: https://freeuni-digital-technologies.github.io/developer-wiki
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
  features:
    - navigation.instant
      #- navigation.indexes
      #- navigation.tabs
    - navigation.sections
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - include-markdown
